book:
  existing: 
    isbn: 9780111222333
    id: "bb97f7fb-7e46-4b99-93bb-47dd5c86c6bb"
    title: "Two Heads are Better Than One"
  invalid:
    id: "Totallynotaguid"

contributor:
  existing:
    id: "4f234bca-4d28-41f8-b17b-6b61a0a5daa2"
    names:
      display: "Zaphod Beeblebrox"
  invalid:
    id: "Totallynotaguid"
