book:
  existing: 
    isbn: 9780111222333
    id: "16df6d65-8b87-46b2-9fe5-27e7934c77e1"
    title: "Two Heads are Better Than One"
  invalid:
    id: "Totallynotaguid"

contributor:
  existing:
    id: "682b83a8-01a8-4e5a-bbf3-6c4f303a0058"
    names:
      display: "Zaphod Beeblebrox"
  invalid:
    id: "Totallynotaguid"
