# This file details the various servers in each environment which tests for this service require.
local:
  servers:
    api: http://localhost:7017/
    health: http://localhost:7017/health

dev_int:
  servers:
    api: https://api.dev.bbbtest2.com/
    health: http://kinney.blinkbox.local:7017/health
